// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for teste documents */
type TesteDocumentData = Record<string, never>;
/**
 * teste document from Prismic
 *
 * - **API ID**: `teste`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TesteDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TesteDocumentData>, "teste", Lang>;
export type AllDocumentTypes = TesteDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { TesteDocumentData, TesteDocument, AllDocumentTypes };
    }
}
